redis:
  container_name: gnrb-redis
  image: redis:3-alpine
  ports:
    - "$REDIS_PORT:6379"

postgres:
  container_name: gnrb-postgres
  image: postgres:9
  environment:
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_DB=$POSTGRES_DB
  ports:
    - "$POSTGRES_PORT:5432"

elasticsearch:
  container_name: gnrb-elasticsearch
  image: elasticsearch:2.4.2
  ports:
    - "$ELASTICSEARCH_PORT:9200"

rabbitmq:
  container_name: gnrb-rabbitmq
  image: rabbitmq:3.6.5-management
  ports:
    - "$RABBITMQ_PORT:5672"
    - "$RABBITMQ_MANAGEMENT_PORT:15672"
  environment:
    - "RABBITMQ_DEFAULT_USER=$RABBITMQ_USER"
    - "RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD"
    - "RABBITMQ_DEFAULT_VHOST=$RABBITMQ_VHOST"

etcd:
  container_name: gnrb-etcd
  image: quay.io/coreos/etcd:v2.2.2
  ports:
    - "$ETCD_PORT:2379"
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
